services:
  traefik:
    image: traefik:v3.1.5@sha256:7b927f0ab22c85a636cde667aa6a3c90f1967bb5079899ce960ec51454fc96e9
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_letsencrypt:/letsencrypt"
      - "./config:/etc/traefik"
    networks:
      - default
      - reverse-proxy
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${ACME_EMAIL:?}
      - PORTAINER_HOSTNAME=${PORTAINER_HOSTNAME:?}

volumes:
  traefik_letsencrypt:

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
