services:
  traefik:
    image: traefik:v3.1.6@sha256:f703a2ac2ddf75f6e06c9cccac7f158765e2ab42d642b04e79e2e3d7355c2ddc
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_letsencrypt:/letsencrypt"
      - "./config:/etc/traefik"
    networks:
      - default
      - reverse-proxy
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${ACME_EMAIL:?}
      - PORTAINER_HOSTNAME=${PORTAINER_HOSTNAME:?}

volumes:
  traefik_letsencrypt:

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
